baseURL = "https://tailwind-elements.com/"
languageCode = "en-us"
title = "Tailwind Elements - Bootstrap components recreated with Tailwind"
theme = "ga-hugo-theme"
enableInlineShortcodes = "true"

[params]
recaptchaPublicKey = "6Ld6dIgkAAAAAIpY7wJD8aZnFAWF-S1O5HOtdItU"
